"""D-CERT (IL track), sprint 2026-08-05-defs-il-certification, C2, Job 4.

The certification's BACKBONE test: every candidate SPAN in the full
population carries exactly one cluster_id. This is the mechanical
assertion "every candidate is classified" is actually about -- without
it, that claim is a statement about a spreadsheet, never about the
corpus.

## Population and provenance (no corpus read here -- program standing
## constraint)

This test reads `backend/tests/fixtures/certification/c1_span_population.
jsonl` -- a COMMITTED, VENDORED manifest, generated by the committed
script `backend/tests/certification/c1_denominator.py` against the real,
read-only corpus. That script is explicitly NOT part of `pytest`
(the same "never part of pytest" discipline `ingest_wiki_corpus_cli.py`'s
own docstring states for the same reason: no test may read or download
the real corpus). This test reads only the committed, vendored OUTPUT of
that script -- the same relationship every other `_live.py` integration
test in this suite has to its own vendored `.wiki` excerpt fixtures,
just at corpus scale (93,509 rows) instead of a handful of hand-picked
files. **Integrity pin:** `backend/tests/fixtures/certification/
c1_span_population.sha256` -- QA re-runs the script and diffs the hash
(C5), independent of this test's own row-count pin below.

## ROUND 2 (M33-2): the population count changed, and the delta is
## explained here, not silently re-pinned

`c1_denominator.py`'s cluster-1 predicate was refined (ruling M33-2 --
the standalone-vav-conjunction false positive, e.g. `"רכב" ו"דרך"`, is no
longer misclassified word-internal). Re-running the script after that
fix changes the population from 91,764 (Round 1) to **93,509** (Round 2)
-- MORE eligible characters means MORE candidate spans, not fewer, which
is the expected direction (the fix REMOVES a false exclusion, it does
not add one). See `c1_denominator.py`'s own docstring, "The vav-
conjunction correction, APPLIED", for the full mechanism and the
independent confirmation (the unrelated `unpaired_trailing_quotes`
diagnostic dropped 83%, 1,676 -> 282 articles). The refined predicate
also has its own dedicated unit test:
`backend/tests/unit/test_certification_clusters_word_internal_quote.py`.

## Why this is the FULL population, not a sample

C2's own text is explicit: "Sampling does not substitute for it: C2 is
over the whole population, always." This test iterates every row in the
manifest -- currently 93,509, the real, whole, re-derived candidate-span
population (see `c1_denominator.py`'s own docstring for why this is not
the naive eligible/2 estimate -- 282 articles still have an odd
eligible-quote count, and this script's PER-ARTICLE pairing correctly
declines to force a cross-article pairing rather than silently
manufacturing a bogus span).

## A resolution of an ambiguity in the contract's own text, applied here

The contract's cluster-1 disposal count (33.1% of 276,815 raw quote
CHARACTERS) and C2's own "~92,600-row population" (the paired SPAN count)
are two different granularities. `clusters.py`'s own module docstring
names this explicitly and adopts a two-level resolution: Level 0
(character level, cluster 1 only) is total and disjoint BY CONSTRUCTION
(every character is Hebrew-letter-flanked or not -- there is no third
option, so this partition needs no corpus-scale row iteration to prove
exhaustive; falsifying it would require finding a character for which
`is_word_internal_quote` raises or returns something other than a
boolean, which its own implementation makes impossible). Level 1 (span
level, clusters 2+) is what THIS test iterates, matching C2's own
"~92,600-row population" wording literally. **RULED (M33-1): CONFIRMED
as this Planner originally resolved it** -- no longer an open question.

## Expected RED, and why

The cluster set is incomplete by construction this round (Job 3's own
instruction: "propose the initial cluster set... do not attempt all
20-40"). Three span-level clusters are implemented today
(`wiki_table_markup_attribute`, `production_captured`,
`interpretation_laws_never_reached`); seven more are PROPOSED but not
implemented (`clusters.PROPOSED_CLUSTERS`) -- Round 2 removed one
(the vav-conjunction refinement, now APPLIED to cluster 1 itself, not a
span-level proposal) and added one (`numberless_at_marker_zero_article_
files`, found while building the heading population). This test is RED
because a large number of rows -- genuinely uncaptured spans that do not
yet match any implemented predicate -- are correctly UNASSIGNED, and
because a small number of rows are DOUBLE-assigned (see below, a genuine
finding, not a test bug).
"""

from __future__ import annotations

import json
import pathlib

import pytest

from tests.certification import clusters

_MANIFEST_PATH = (
    pathlib.Path(__file__).resolve().parents[1] / "fixtures" / "certification" / "c1_span_population.jsonl"
)


def _load_rows() -> list[dict]:
    if not _MANIFEST_PATH.exists():
        pytest.fail(
            f"{_MANIFEST_PATH} is missing. This test reads a COMMITTED, "
            "vendored manifest -- it must never read the corpus itself. "
            "Regenerate it with: backend/.venv/bin/python "
            "backend/tests/certification/c1_denominator.py"
        )
    rows: list[dict] = []
    with _MANIFEST_PATH.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def test_manifest_is_the_real_whole_population_not_a_sample():
    """Sanity gate on the fixture itself, so a truncated or stale manifest
    fails loudly here rather than silently passing a smaller population
    below. 93,509 is `c1_denominator.py`'s own measured, reproduced
    output POST the M33-2 vav-conjunction fix (Round 1's own pin was
    91,764, pre-fix -- see this file's own module docstring, "ROUND 2",
    for why the delta is expected and explained, not absorbed) -- an
    exact pin, not a range, so any future re-run that changes this
    number must update this pin deliberately (C5: QA re-runs and diffs,
    this is the diff target)."""
    rows = _load_rows()
    assert len(rows) == 93509, (
        f"expected the full re-derived candidate-span population "
        f"(93,509 rows, c1_denominator.py's own measured output, post-"
        f"M33-2); got {len(rows)}. Either the manifest is stale/"
        f"truncated, or the corpus/production extraction/cluster-1 "
        f"predicate changed -- re-run c1_denominator.py and confirm the "
        f"new count deliberately before updating this pin."
    )


def test_c2_every_span_carries_exactly_one_cluster_id():
    """THE BACKBONE TEST. Runs every registered span-level cluster
    predicate (`clusters.SPAN_CLUSTERS`) over the FULL 93,509-row
    population and asserts zero unassigned, zero double-assigned.

    Expected RED this round, for TWO distinct, both genuinely informative
    reasons (not one blended failure):

    1. UNASSIGNED (the large majority of the failure): spans not yet
       matching any implemented predicate. This is the honest, expected
       state of an intentionally incomplete first-round cluster set --
       see `clusters.PROPOSED_CLUSTERS` for what would close each named
       chunk of this remainder.
    2. DOUBLE-ASSIGNED (small, and NOT swept under the unassigned
       number): a handful of spans match BOTH `wiki_table_markup_
       attribute` and `production_captured` -- a genuine, real
       precision bug in the shipped product this classification pass
       found (not a bug in this test). CORRECTED in Round 2 -- this
       docstring named the WRONG law in its first version (`חוק זכיון ים
       המלח`, which is unrelated -- that law is the complement scout's
       own unquoted-definitions finding). The real source, confirmed by
       BOTH this Planner and independently by the panel manager: `צו
       המועצות המקומיות (מועצה מקומית תעשייתית נאות חובב)` art.1
       (heading `הגדרות`, a real definitions-heading article). Its real,
       unmodified `HebrewProfile` dispatch produces **19 candidates, 8
       of them spurious** -- including one `DefinitionCandidate` carrying
       **seven** `'ltr'` terms at once (`dir="ltr"` HTML-table markup
       swallowed as if it were a defined term, with leftover `<span>`
       tag fragments captured as the "qualifier"). The 15 double-
       assigned spans in THIS test's own count understate the bug's true
       size -- they count only spans that also happen to be markup-
       flagged; the panel manager's own live re-run of the real dispatch
       is the more complete measurement. See the sprint log's Round-2
       entry for the full trace.
    """
    rows = _load_rows()

    unassigned: list[dict] = []
    double_assigned: list[tuple[dict, list[str]]] = []

    for row in rows:
        assigned = clusters.assign_span_clusters(row)
        if len(assigned) == 0:
            unassigned.append(row)
        elif len(assigned) > 1:
            double_assigned.append((row, assigned))

    failure_lines = []
    if unassigned:
        sample = unassigned[:5]
        failure_lines.append(
            f"{len(unassigned)}/{len(rows)} spans are UNASSIGNED (match no "
            f"implemented cluster predicate). Sample: "
            + "; ".join(
                f"{r['file']} art.{r['article_number']} {r['term_text']!r}" for r in sample
            )
        )
    if double_assigned:
        sample = double_assigned[:5]
        failure_lines.append(
            f"{len(double_assigned)}/{len(rows)} spans are DOUBLE-ASSIGNED "
            f"(match more than one cluster predicate -- a genuine "
            f"precision finding, see this test's own docstring). Sample: "
            + "; ".join(
                f"{r['file']} art.{r['article_number']} {r['term_text']!r} -> {ids}"
                for r, ids in sample
            )
        )

    assert not failure_lines, (
        "C2 backbone exhaustiveness/disjointness FAILED (expected this "
        "round -- see this test's own docstring for why):\n"
        + "\n".join(failure_lines)
    )


def test_c2_cluster_1_word_internal_quote_is_total_and_boolean():
    """Level 0 (character level, cluster 1 only -- see this module's own
    docstring for the two-level resolution): `is_word_internal_quote` is
    exhaustive+disjoint BY CONSTRUCTION for any two characters, since it
    is a total function returning a plain `bool` with no third outcome.
    This test does not iterate the corpus (no test may); it falsifies the
    ONLY way this predicate's totality could fail -- raising, or
    returning something that is not unambiguously True/False -- against
    every character class actually observed in the real manifest's own
    `term_text` values (a vendored, corpus-derived artifact, not the
    corpus itself) plus the ASCII/whitespace/boundary cases the predicate
    must also handle."""
    rows = _load_rows()
    observed_chars: set[str] = {""}
    for row in rows:
        observed_chars.update(row["term_text"])
    # A handful of structural edge cases every real corpus body can
    # present, on top of every character actually observed in the
    # vendored manifest above.
    observed_chars.update(["\n", "\t", " ", '"', "-", "=", "א", "ת", "ף", "0", "9"])

    for prev_char in observed_chars:
        for next_char in observed_chars:
            result = clusters.is_word_internal_quote(prev_char, next_char)
            assert isinstance(result, bool), (
                f"is_word_internal_quote({prev_char!r}, {next_char!r}) "
                f"returned {result!r}, not a bool -- cluster 1 must be "
                f"total and unambiguous for C2's exhaustiveness argument "
                f"to hold without a corpus-scale character manifest."
            )
