"""C5 regression guard -- US-NY (sprint 2026-08-04-defs-us-markers,
phase-2 Planner A, item A1). NOT a target: these tests pin what today's
REAL pipeline already captures for US-NY, purely via baseline
`_split_into_numbered_blocks` + `_leading_quote_candidate` -- US-NY has
ZERO family-3 rules registered against it (no EntrySplitterRule/
TermClauseRule matches `"US-NY"` or `"US-*"` anywhere in
`backend/app/definition_links/rules/`, confirmed by grep before writing
this file). US-NY is one of the five C5 working-baseline regression-guard
states (program doc `2026-08-04-definition-completeness.md`); this sprint's
zero-yield extension work must not silently shrink, duplicate, or corrupt
any of the captures pinned below. GREEN NOW; would fail if a future rule
(this panel's own A4 widening, or anyone else's) changed or swallowed
these baseline captures.

Each row's exact term SET is pinned (a regression that drops, merges, or
duplicates a term changes the set) plus one full `definition_text` pin per
row (a content-fidelity spot check, not exhaustive -- rows here carry up
to 21 terms; pinning every
one's full text would bloat this file past the 300-line convention for
marginal extra protection over the term-set check)."""

from __future__ import annotations

import json
from pathlib import Path

from app.definition_links.ingest_us_statutes import ingest_us_statute_rows
from app.definition_links.pipeline import run_definition_linking
from app.models.definition import Definition

FIXTURE_PATH = (
    Path(__file__).resolve().parents[1] / "fixtures" / "us_statutes" / "us_markers_c5guard_ny_rows.json"
)


def _load_rows() -> dict[str, dict]:
    return {r["act_id"]: r for r in json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))}


def _run(db_session, matter_with_users, act_id: str):
    rows = _load_rows()
    row = rows[act_id]
    ingest_us_statute_rows(
        db_session,
        repository_id=matter_with_users["repository_id"],
        matter_id=matter_with_users["matter_id"],
        title=f"{act_id} C5 guard",
        rows=[{k: v for k, v in row.items() if not k.startswith("_")}],
        jurisdiction="US-NY",
    )
    result = run_definition_linking(
        db_session,
        matter_id=matter_with_users["matter_id"],
        triggered_by_user_id=matter_with_users["contributor_id"],
    )
    definitions = [db_session.get(Definition, d["id"]) for d in result["created_definitions"]]
    by_term = {}
    for d in definitions:
        for t in d.terms:
            by_term[t] = d
    return by_term


def test_c5_guard_state_ny_aenv_a27_t18_s27_1803(db_session, matter_with_users):
    """STATE_NY_AENV_A27_T18_S27-1803: pins 1 term(s) as currently captured by baseline
    alone. Regression guard -- not a target."""
    by_term = _run(db_session, matter_with_users, "STATE_NY_AENV_A27_T18_S27-1803")
    assert sorted(by_term) == ['rechargeable battery'], f"got {sorted(by_term)!r}"
    spot = by_term['rechargeable battery']
    assert spot.definition_text.strip() == 'shall not include a battery used as the\nprincipal electric power source for a vehicle other than as set forth in\nsubparagraph (ii) of paragraph (a) of this subdivision, such as, but not\nlimited to, an automobile, boat, truck, tractor, golf cart or\nwheelchair; for storage of electricity generated by an alternative power\nsource, such as solar or wind-driven generators; or for memory backup\nthat is an integral component of an electronic device;\n  5. "retailer" means a person, firm or corporation that engages in the\nsale of rechargeable batteries, or products containing such batteries,\nto a consumer in the state, including, but not limited to, transactions\nconducted through sales outlets, catalogs, by mail, telephone or the\ninternet. For the purposes of this section retailer shall not include a\nfood store; and\n  6. "food store" means a store selling primarily food and food products\nfor consumption or use off the premises that occupies less than fourteen\nthousand square feet of display space.\n  7. "sell" or "sale" means any transfer for consideration of title or\nthe right to use, from a manufacturer or retailer to a person,\nincluding, but not limited to, transactions conducted through retail\nsales outlets, catalogs, mail, the telephone, the internet, or any\nelectronic means; "sell" or "sale" shall not include samples, donations,\nand reuse.', (
        f"content-fidelity spot check failed for 'rechargeable battery': got {spot.definition_text!r}"
    )

def test_c5_guard_state_ny_agct_a2_k_s25_ff(db_session, matter_with_users):
    """STATE_NY_AGCT_A2-K_S25-FF: pins 15 term(s) as currently captured by baseline
    alone. Regression guard -- not a target."""
    by_term = _run(db_session, matter_with_users, "STATE_NY_AGCT_A2-K_S25-FF")
    assert sorted(by_term) == ['Aggregate employment shares', 'Eligible aggregate employment shares', 'Eligible business', 'Eligible premises', 'Employment share', 'Full-time work week', 'Hotel services', 'Linear scalar', 'Maximum approved employment shares', 'Mayor', 'Part-time work week', 'Person', 'Program total', 'Relocate', 'Retail activity'], f"got {sorted(by_term)!r}"
    spot = by_term['Employment share']
    assert spot.definition_text.strip() == "means, for each employee, partner or sole\nproprietor of an eligible business, the sum of: (1) the number of\nfull-time work weeks worked by such employee, partner or sole proprietor\nduring the eligible business's taxable year divided by the number of\nweeks in the taxable year; and (2) the number of part-time work weeks\nworked by such employee, partner or sole proprietor during the eligible\nbusiness's taxable year divided by an amount equal to twice the number\nof weeks in the taxable year. Employment share shall not include\nfull-time or part-time work weeks attributable to employees, partners or\nsole proprietors acquired by an eligible business as a result of a\nmerger with, acquisition of another person, or a transaction having a\ncomparable effect, that occurs after June thirtieth, two thousand\ntwenty-five, and before the end of the taxable year in which a credit is\nclaimed by such eligible business pursuant to a local law enacted in\naccordance with section twenty-five-gg of this article, or to\nsuccessors, if any, to those employees, partners or sole proprietors.", (
        f"content-fidelity spot check failed for 'Employment share': got {spot.definition_text!r}"
    )

def test_c5_guard_state_ny_afct_a10_c_s1092(db_session, matter_with_users):
    """STATE_NY_AFCT_A10-C_S1092: pins 6 term(s) as currently captured by baseline
    alone. Regression guard -- not a target."""
    by_term = _run(db_session, matter_with_users, "STATE_NY_AFCT_A10-C_S1092")
    assert sorted(by_term) == ['Interested adult', 'caretaker', 'commissioner of social services', 'destitute child', 'parent', 'permanency hearing'], f"got {sorted(by_term)!r}"
    spot = by_term['caretaker']
    assert spot.definition_text.strip() == 'shall mean a person or persons, other than a parent of\na child alleged or adjudicated to be a destitute child pursuant to this\narticle, who possesses a valid, current court order providing him or her\nwith temporary or permanent guardianship or temporary or permanent\ncustody of said child.', (
        f"content-fidelity spot check failed for 'caretaker': got {spot.definition_text!r}"
    )

def test_c5_guard_state_ny_aujc_a21_s2101(db_session, matter_with_users):
    """STATE_NY_AUJC_A21_S2101: pins 21 term(s) as currently captured by baseline
    alone. Regression guard -- not a target."""
    by_term = _run(db_session, matter_with_users, "STATE_NY_AUJC_A21_S2101")
    assert sorted(by_term) == ['Administrative board', 'Administrative judge', 'Appellate division', 'City', 'City justice', 'Clerk', 'County', 'County clerk', 'Court', 'Court established in and for a city', 'Enforcement officer', 'Justice', 'Municipal board', 'Municipality', 'Rules', 'Town', 'Town court', 'Town justice', 'Village', 'Village court', 'Village justice'], f"got {sorted(by_term)!r}"
    spot = by_term['Court']
    assert spot.definition_text.strip() == 'embraces each and every court or office to which this act\nis applicable pursuant to § 2300 and, for purposes of the application of\nthis act to each such court, it shall be taken as a reference to either:\n  1. the town court of the particular town; or\n  2. the village court of the particular village, and if there is no\ncourt established in and for the particular village it means the town\ncourt, if any, of the town in which the village is located in whole or\nin part; or\n  3. the court established in and for the particular city, if such court\nis governed by this act; as the case may be.', (
        f"content-fidelity spot check failed for 'Court': got {spot.definition_text!r}"
    )

def test_c5_guard_state_ny_aisc_a71_s7101(db_session, matter_with_users):
    """STATE_NY_AISC_A71_S7101: pins 7 term(s) as currently captured by baseline
    alone. Regression guard -- not a target."""
    by_term = _run(db_session, matter_with_users, "STATE_NY_AISC_A71_S7101")
    assert sorted(by_term) == ['Acquisition of assets', 'Company', 'Consolidated company', 'Consolidation', 'Constituent company', 'Merger', 'Surviving company'], f"got {sorted(by_term)!r}"
    spot = by_term['Acquisition of assets']
    assert spot.definition_text.strip() == 'and "acquire the assets of", means the\nacquisition through the purchase or otherwise of all or substantially\nall of the assets of a domestic company or of any company by a domestic\ncompany.', (
        f"content-fidelity spot check failed for 'Acquisition of assets': got {spot.definition_text!r}"
    )

def test_c5_guard_state_ny_apbh_a34_t1_s3400(db_session, matter_with_users):
    """STATE_NY_APBH_A34_T1_S3400: pins 12 term(s) as currently captured by baseline
    alone. Regression guard -- not a target."""
    by_term = _run(db_session, matter_with_users, "STATE_NY_APBH_A34_T1_S3400")
    assert sorted(by_term) == ['Advertisement', 'Burial', 'Embalmer', 'Embalming', 'Embalming fluid', 'Funeral directing', 'Funeral director', 'Funeral establishment', 'Funeral firm', 'Registered resident', 'Undertaker', 'Undertaking'], f"got {sorted(by_term)!r}"
    spot = by_term['Registered resident']
    assert spot.definition_text.strip() == 'means a person who passed a funeral\ndirecting examination and who is duly registered as such with the\ndepartment while in the employ of a registered funeral firm and who is\nengaged in the practice of funeral directing under the supervision of a\nlicensed funeral director or undertaker and embalmer; provided, however,\nthat a registered resident shall not have authority to sign any form or\ndocument required by law which requires the signature of a licensed\nfuneral director or make funeral arrangements or own or manage a funeral\nfirm.', (
        f"content-fidelity spot check failed for 'Registered resident': got {spot.definition_text!r}"
    )
